committing to create an image; terraform still wip- BROKEN

diff --git a/modules/install-vault/install-vault b/modules/install-vault/install-vault
--- a/modules/install-vault/install-vault
+++ b/modules/install-vault/install-vault
@@ -6,14 +6,11 @@
 
 set -e
 
-readonly DEFAULT_INSTALL_PATH="/opt/vault"
+readonly DEFAULT_INSTALL_PATH="/etc/vault"
 readonly DEFAULT_VAULT_USER="vault"
 
 readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 readonly SYSTEM_BIN_DIR="/usr/local/bin"
-
-readonly SUPERVISOR_DIR="/etc/supervisor"
-readonly SUPERVISOR_CONF_DIR="$SUPERVISOR_DIR/conf.d"
 
 readonly SCRIPT_NAME="$(basename "$0")"
 
@@ -67,27 +64,29 @@ function assert_not_empty {
   fi
 }
 
-# Install steps are based on: http://unix.stackexchange.com/a/291098/215969
-function install_supervisord {
-  sudo apt-get install -y supervisor
-  sudo update-rc.d supervisor defaults
-
-  create_supervisor_config
-  sudo systemctl enable supervisor
+function has_yum {
+  [ -n "$(command -v yum)" ]
 }
 
-function create_supervisor_config {
-  sudo mkdir -p "$SUPERVISOR_CONF_DIR"
-  sudo cp "$SCRIPT_DIR/supervisord.conf" "$SUPERVISOR_DIR/supervisord.conf"
+function has_apt_get {
+  [ -n "$(command -v apt-get)" ]
 }
 
 function install_dependencies {
   log_info "Installing dependencies"
 
+  if $(has_apt_get); then
     sudo apt-get update -y
-    sudo apt-get install -y azure-cli curl unzip jq
-    install_supervisord
+    sudo apt-get install -y curl unzip jq
+  elif $(has_yum); then
+    sudo yum update -y
+    sudo yum install -y curl unzip jq
+  else
+    log_error "Could not find apt-get or yum. Cannot install dependencies on this OS."
+    exit 1
+  fi
 }
+
 
 function user_exists {
   local readonly username="$1"
@@ -130,8 +129,7 @@ function install_binaries {
   local readonly download_path="/tmp/vault_${version}_linux_amd64.zip"
   local readonly bin_dir="$path/bin"
   local readonly vault_dest_path="$bin_dir/vault"
-  local readonly run_vault_dest_path="$bin_dir/run-vault"
-
+  
   log_info "Downloading Vault $version from $url to $download_path"
   curl -o "$download_path" "$url"
   unzip -d /tmp "$download_path"
@@ -148,11 +146,6 @@ function install_binaries {
     log_info "Adding symlink to $vault_dest_path in $symlink_path"
     sudo ln -s "$vault_dest_path" "$symlink_path"
   fi
-
-  log_info "Copying Vault run script to $run_vault_dest_path"
-  sudo cp "$SCRIPT_DIR/../run-vault/run-vault" "$run_vault_dest_path"
-  sudo chown "$username:$username" "$run_vault_dest_path"
-  sudo chmod a+x "$run_vault_dest_path"
 }
 
 # For more info, see: https://www.vaultproject.io/docs/configuration/#disable_mlock
